language: objective-c
#osx_image: xcode8.2
#xcode_project: ios/AwesomeProject.xcodeproj
#xcode_sdk: iphonesimulator9.2

script:
  - xcodebuild -project ios/AwesomeProject.xcodeproj -scheme AwesomeProject -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
  - xcodebuild test -project ios/AwesomeProject.xcodeproj -scheme AwesomeProject -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
env:
  global:
    secure: YRkT8Wff3udW4diymm/NB1wEg22rSz+S/RowlG6li3eE//RtCPLNrBSmazGNpw9UuDvBApc0EneuYgt6hGdXQSMURg5dtvcd5VTd5qbtwuAKy0d5IOjtdZA0KKeibsYqjoXnKNdTaP0cgpi52dHSQO9YdGUzUXzDcG5Jys30gwnekecYsKvXcvZoTdtRIUHnwHteuJNEWzG+o3uCAqTltvPWiFOQ1a41GKh695EOlYXLMwPAinB9n4zbGVpJeOb5KgMl5/KhrJYSeaCkJ589EBImmHILZj9X7e/hIW4Wuumktj38J59Q/elWWMADMNkqu9+n14yI6ughNEOSs8ONqw7Pqysgw3dOHQdHKuL+6PIz3BjutWvurawSk4ULpP3EJjs3e4Gl989uS/vKwsK9R/d0UsNtnMORMxShv9qnWIVFBktwPShaRBW6DvS+/AS9epD0pdSNHDT4owXULhTE19ab67RjDxFDDB7LzTJBSyd/7/QeckbaJ6iIbcJbrcA8TojM7VXDexsk5Y/M9CV8sSVTecwMDQd2AYOjpLPXfwJy2IOD/f8VqDRT8OIZyqoWIsUJDqUitslZY96Hpf89jAqPlAXfP4K2JmjBYsuZnyyBJG6ZNqtNaW5FtESh38eyfQYcK2dxu9dwoWDoeYU0KI+gvVKZuVDptvdcRNVD7do=
